version: '3'

volumes:
  static:

services:
  frontend:
    image: registry.gitlab.com/lacolle87/cr/nitrojam_frontend:latest
    volumes:
      - static:/app/result_build
    command: /bin/sh -c "cp -r /app/build/. /app/result_build/"

  nginx:
    image: registry.gitlab.com/lacolle87/cr/nitrojam_nginx:latest
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - static:/usr/share/nginx/html
    depends_on:
      - frontend