version: '3'

volumes:
  static:

services:
  frontend:
    build:
      context: ./react
      dockerfile: Dockerfile
    volumes:
      - static:/app/result_build
    command: /bin/sh -c "cp -r /app/dist/. /app/result_build/"

  nginx_nj:
    build:
      context: ./nginx
      dockerfile: Dockerfile
    restart: always
    ports:
      - "9000:80"
    volumes:
      - ./nginx:/etc/nginx/conf.d
      - ./images:/images
      - static:/usr/share/nginx/html
    depends_on:
      - frontend